/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



import java.util.*;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Gowtham
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        repaword = new javax.swing.JPasswordField();
        pawordd = new javax.swing.JPasswordField();
        urname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        signn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addres = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        calender = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        register.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        register.setText("REGISTER HERE");
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 25, 110, 10));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("First Name: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 55, 80, 10));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Last Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 105, 70, 10));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("UserName:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 135, 60, 10));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 175, 70, 10));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Repassword:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 80, 10));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 328, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 50, 20));
        getContentPane().add(repaword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 100, 30));

        pawordd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paworddActionPerformed(evt);
            }
        });
        getContentPane().add(pawordd, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 172, 100, 30));
        getContentPane().add(urname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 100, 30));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 92, 100, 30));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 100, 30));

        signn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        signn.setText("save");
        signn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signnActionPerformed(evt);
            }
        });
        getContentPane().add(signn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 70, 20));

        addres.setColumns(20);
        addres.setRows(5);
        jScrollPane1.setViewportView(addres);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 110, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Dob");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 50, 20));
        getContentPane().add(calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, 23));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 23));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 23));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, 23));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setText("back to login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 380, 110, 23));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paworddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paworddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paworddActionPerformed

    private void signnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signnActionPerformed
        
      
      String firstname=fname.getText();
      String lastname=lname.getText();
      String username=urname.getText();
      String password=String.valueOf(pawordd.getPassword());
      String retype=String.valueOf(repaword.getPassword());
     
      String address=addres.getText();
       SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd"); 
      String Dob=dateformat.format(calender.getDate());
              
       PreparedStatement ps;
String query="INSERT INTO `user_details`(`first_name`,`Last_name`,`User_name`,`Pass_word`,`Repass_word`,`Address`,`Date_of_birth`)values(?,?,?,?,?,?,?)";
try{
    ps=MyConnection1.getConnection().prepareStatement(query);
    
    ps.setString(1,firstname);
    ps.setString(2,lastname);
    ps.setString(3,username);
    ps.setString(4,password);
    ps.setString(5,retype);
    
    ps.setString(6,address);
    ps.setString(7,Dob);
    if(ps.executeUpdate()>0){
           
        JOptionPane.showMessageDialog(null, "new user add");
    }
}catch(Exception ex)
            {
            System.out.println(ex);
            
    
            }  
    }//GEN-LAST:event_signnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String Firstname = fname.getText();
        ResultSet rs;

        try {
            String query = "SELECT * FROM user_details where First_Name=?";

            PreparedStatement ps = MyConnection1.getConnection().prepareStatement(query);
            ps.setString(1, Firstname);
            rs = ps.executeQuery();
            if (rs.next()) {
                lname.setText(rs.getString(2));
               urname.setText(rs.getString(3));
                pawordd.setText(rs.getString(4));
               
                repaword.setText(rs.getString(5));
                
                addres.setText(rs.getString(6));
                calender.setDate(rs.getDate(7));
                               } 
            else {
                JOptionPane.showMessageDialog(null, "FirstName Does Not Exist");
               }

            } catch (Exception ex) {
            System.out.println(ex);

}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String Firstname= fname.getText();
        int a = JOptionPane.showConfirmDialog(null, "Your Are Delete", "", JOptionPane.YES_NO_OPTION);
        PreparedStatement ps;

        if (a == 0) {
            String query = "DELETE FROM user_details WHERE first_name=?";
            try {

                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, Firstname);
                if (ps.executeUpdate() > 0) {

                    JOptionPane.showMessageDialog(null, "Recorded Deleted Successfully...!!!! ");
                } else {
                    JOptionPane.showMessageDialog(null, "Any One Does ot exits");

                }
            } catch (Exception ex) {
                ex.printStackTrace();

        }

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 login s=new login();
      s.setVisible(true);
      this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String firstname=fname.getText();
        System.out.println(firstname);
        String lastname=lname.getText();
        String username=urname.getText();
        String password=String.valueOf(pawordd.getPassword());
        String retype=String.valueOf(repaword.getPassword());

        String address=addres.getText();
        SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
        String Dob=dateformat.format(calender.getDate());
        PreparedStatement ps;

        String query = "UPDATE user_details SET first_name=?,Last_name=?,User_name=?,pass_word=?,Repass_word=?,Address= ?,WHERE Date_of_birth=?";

        try {
            ps=MyConnection1.getConnection().prepareStatement(query);
            ps.setString(1,firstname);
            ps.setString(2,lastname);
            ps.setString(3,username);
            ps.setString(4,password);
            ps.setString(5,retype);
            ps.setString(6,address);
            ps.setString(7,Dob);

            if (ps.executeUpdate() > 0) {

                JOptionPane.showMessageDialog(null, "Update Successfully....!!!!");
            } else {
                JOptionPane.showMessageDialog(null, "Any One does not exist");
            }
        } catch (java.sql.SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE,null,ex);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buyerdetails s=new buyerdetails();
        s.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addres;
    private com.toedter.calendar.JDateChooser calender;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pawordd;
    private javax.swing.JLabel register;
    private javax.swing.JPasswordField repaword;
    private javax.swing.JButton signn;
    private javax.swing.JTextField urname;
    // End of variables declaration//GEN-END:variables
}
